version: 2

project_name: go-semver-audit

before:
  hooks:
    - go mod tidy

builds:
  - id: go-semver-audit
    main: ./cmd/go-semver-audit
    binary: go-semver-audit
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - id: binaries
    builds:
      - go-semver-audit
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"

changelog:
  disable: true

release:
  draft: false
  prerelease: false

